baseURL = 'https://juiceblogs.vercel.app/'
languageCode = 'en-us'
title = 'Juice Blog'
favico = true

paginate = 4

[params]
 description = "The page where you get notes."
 dateFormat = "Jan 2, 2006"

[taxonomies]
 category = "categories"
 author = "authors" 

[markup]
  defaultMarkdownHandler = 'goldmark'

ignoreLogs = ['warning-goldmark-raw-html']